def options(opt):
    opt.load('compiler_c')
    opt.load('python')
    opt.load('cython')

def configure(conf):
    conf.load('compiler_c')
    conf.load('python')
    conf.check_python_headers()
    conf.load('cython')

def build(bld):
    bld.recurse('foo')
